webSites/webSites/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webSitesApp.urls')),
    path('webSitesApp/', include('webSitesApp.urls'))
]

webSites/webSitesApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Websites.as_view(), name='websites'),
    path('websites', views.Websites.as_view(), name='websites-no-cat'),
    path('websites_filter/<str:category>', views.Websites.as_view(), name='websites-cat'),
    path('websites_order/<str:ordering>', views.Websites.as_view(), name='website-ord'),
    path('website/<int:pk>', views.WebsitesDetailView.as_view(), name='website-detail'),
    path('create_website/', views.CreateWebsite.as_view(), name='create-website'),
    path('create_webpage/', views.CreateWebPage.as_view(), name='create-webpage'),
    path('categories/', views.CategoriesList.as_view(), name='categories'),
    path('create_category/', views.CreateCategory.as_view(), name='create-category'),
    path('download_websites/', views.DownloadWebsites.as_view(), name='download-websites')
]

webSites/webSitesApp/models.py
from django.db import models
from django.urls import reverse


class Website(models.Model):
    url = models.CharField(max_length=1000)
    title = models.CharField(max_length=200)
    meta_description = models.CharField(max_length=500)
    alexa_rank = models.IntegerField()
    category = models.ForeignKey('WebsiteCategory', on_delete=models.SET_NULL, null=True)
    date_added = models.DateField(null=True, blank=True)
    date_updated = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('website-detail', args=[str(self.id)])


class WebsiteCategory(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=1000)
    date_added = models.DateField(null=True, blank=True)
    date_updated = models.DateField(null=True, blank=True)
    count = models.IntegerField()

    def __str__(self):
        return self.name


class WebPage(models.Model):
    website = models.ForeignKey('Website', on_delete=models.SET_NULL, null=True)
    url = models.CharField(max_length=1000, unique=True)
    date_added = models.DateField(null=True, blank=True)
    date_updated = models.DateField(null=True, blank=True)
    title = models.CharField(max_length=200)
    meta_description = models.CharField(max_length=500)

    def __str__(self):
        return self.url

webSites/webSitesApp/views.py
from django.views.generic import ListView, DetailView, CreateView
from .models import Website, WebPage, WebsiteCategory
from django.urls import reverse_lazy
import datetime
from webSites.tasks import *


class Websites(ListView):
    model = Website
    template_name = "websites.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        categories = WebsiteCategory.objects.all()
        data['categories'] = categories
        field_names = ['url', 'title', 'date_added', 'date_updated']
        data['field_names'] = field_names
        return data

    def get_queryset(self):
        if "category" in self.kwargs:
            category = WebsiteCategory.objects.filter(name=self.kwargs['category'])[0]
            self.request.session['category'] = category.name
            return Website.objects.filter(category=category)
        if "ordering" in self.kwargs:
            if self.request.session['category'] == "all":
                return Website.objects.all().order_by(self.kwargs['ordering'])
            else:
                category_name = self.request.session['category']
                category = WebsiteCategory.objects.filter(name=category_name)[0]
                return Website.objects.filter(category=category).order_by(self.kwargs['ordering'])
        else:
            self.request.session['category'] = "all"
            return Website.objects.all()[:10]


class WebsitesDetailView(DetailView):
    model = Website
    template_name = "website_detail.html"


class CreateWebsite(CreateView):
    model = Website
    fields = '__all__'
    now = datetime.datetime.now()
    today = "{}-{}-{}".format(now.year, now.month, now.day)
    initial = {'date_added': today, 'date_updated': today}
    template_name = "website_create.html"
    success_url = reverse_lazy('websites')


class CreateWebPage(CreateView):
    model = WebPage
    fields = '__all__'
    now = datetime.datetime.now()
    today = "{}-{}-{}".format(now.year, now.month, now.day)
    initial = {'date_added': today, 'date_updated': today}
    template_name = "webpage_create.html"
    success_url = reverse_lazy('websites')


class CategoriesList(ListView):
    model = WebsiteCategory
    template_name = "website_category.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        self.get_count()
        return data

    @staticmethod
    def get_count():
        categories = WebsiteCategory.objects.all()
        for category in categories:
            count = Website.objects.filter(category=category).count()
            category.count = count
            category.save()


class CreateCategory(CreateView):
    model = WebsiteCategory
    fields = '__all__'
    now = datetime.datetime.now()
    today = "{}-{}-{}".format(now.year, now.month, now.day)
    initial = {'date_added': today, 'date_updated': today}
    template_name = "category_create.html"
    success_url = reverse_lazy('categories')


class DownloadWebsites(ListView):
    template_name = "download_websites.html"
    model = Website

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        url = "http://s3.amazonaws.com/alexa-static/top-1m.csv.zip"
        out_path = "webSitesApp/static/"
        result = download_file.delay(url, out_path)
        #result = download_file.apply_async(url)
        return data

webSites/webSitesApp/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <title>Web sites</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>

<body>
  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'websites' %}">Websites</a></li>
          <li><a href="{% url 'categories' %}">Categories</a></li>
      </ul>
      {% endblock %}
      </div>
      <div class="col-sm-10 ">

        {% block content %}{% endblock %}

      </div>

    </div>

  </div>

</body>
</html>

webSites/webSitesApp/templates/category_create.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

webSites/webSitesApp/templates/download_websites.html
{% extends "base_generic.html" %}

{% block content %}

<p>Scanning in progress...</p>

{% endblock %}

webSites/webSitesApp/templates/webpage_create.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

webSites/webSitesApp/templates/website_category.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Categories list</h1>

    {% if websitecategory_list %}
    <ul>

      {% for category in websitecategory_list %}
      <li>
        <strong>{{ category.name }}</strong> <br>
        Description: {{ category.description }} <br>
        Date added: {{ category.date_added }} <br>
        Date updated: {{ category.date_updated }} <br>
        Count: {{  category.count }}
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no categories</p>
    {% endif %}

    <a href="{% url 'create-category' %}">Create category</a>
{% endblock %}

webSites/webSitesApp/templates/website_create.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

webSites/webSitesApp/templates/website_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Title: {{ website.title }}</h1>

  <p><strong>url:</strong> {{ website.url }} </p>
  <p><strong>Meta description:</strong> {{ website.meta_description }}</p>
  <p><strong>Alexa rank:</strong> {{ website.alexa_rank }}</p>
  <p><strong>Category:</strong> {{ website.category }}</p>
  <p><strong>Date added:</strong> {{ website.date_added }}</p>
  <p><strong>Date updated:</strong> {{ website.date_updated }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Web pages</h4>

    {% for web_page in website.webpage_set.all %}
      <hr>
      <p><strong>Title:</strong> {{web_page.title}}</p>
      <p><strong>Url:</strong> {{web_page.url}}</p>
      <p><strong>Date added:</strong> {{web_page.date_added}}</p>
      <p><strong>Date updated:</strong> {{web_page.date_updated}}</p>
      <p><strong>Meta description:</strong> {{web_page.meta_description}}</p>
    {% endfor %}
  </div>

{% endblock %}

webSites/webSitesApp/templates/websites.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Websites list</h1>

    {% if website_list %}

      <table class="table">
        <tr>
          <th>
            <a href="{% url 'website-ord' 'title' %}">Title</a>
          </th>
          <th>
            <a href="{% url 'website-ord' 'url' %}">Url</a>
          </th>
          <th>
            <a href="{% url 'website-ord' 'category' %}">Category</a>
          </th>
          <th>
            <a href="{% url 'website-ord' 'date_added' %}">Date added</a>
          </th>
          <th>
            <a href="{% url 'website-ord' 'date_updated' %}">Date updated</a>
          </th>
        </tr>
        {% for website in website_list %}
          <tr>
            <td>
              <a href="{{ website.get_absolute_url }}">{{ website.title }}</a>
            </td>
            <td>
              {{ website.url }}
            </td>
            <td>
              {{ website.category }}
            </td>
            <td>
              {{ website.date_added }}
            </td>
            <td>
              {{ website.date_updated }}
            </td>
          </tr>
        {% endfor %}
      </table>

      <br>
      <p>Filter by category:</p>

      <select onchange="location = this.options[this.selectedIndex].value;">
        <option>Please select</option>
        <option value="{% url 'websites' %}">All</option>
        {% for category in categories %}
        <option value="{% url 'websites-cat' category.name %}">{{category.name}}</option>
        {% endfor %}
      </select>​

      <br><br>

    {% else %}
      <p>There are no websites</p>
    {% endif %}
    <br>
    <a href="{% url 'create-website' %}">Create website</a>
    <br>
    <a href="{% url 'create-webpage' %}">Create webpage</a>
    <br>
    <a href="{% url 'download-websites' %}">Scan websites</a>
{% endblock %}